apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: dd-tracing-logging-examples-nodejs
  name: dd-tracing-logging-examples-nodejs
  namespace: dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dd-tracing-logging-examples-nodejs
    spec:
      containers:
      - env:
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        name: dd-tracing-logging-examples-nodejs
        image: bufferapp/dd-tracing-logging-examples:nodejs
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
